// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfm1A5GOH5CQcgVXebfL0ub4usxyjeHCE',
    appId: '1:532745856576:web:d324b30bebac5c2d88a1a5',
    messagingSenderId: '532745856576',
    projectId: 'nutri-45d59',
    authDomain: 'nutri-45d59.firebaseapp.com',
    storageBucket: 'nutri-45d59.appspot.com',
    measurementId: 'G-YM13XK03LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxi3KaH3ltDSgpCnBxe20eHTysXOE4nY',
    appId: '1:532745856576:android:f0ebc537559b6dd988a1a5',
    messagingSenderId: '532745856576',
    projectId: 'nutri-45d59',
    storageBucket: 'nutri-45d59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9iu0AK9kNcs332t66a6dgu9OHZJuTLM',
    appId: '1:532745856576:ios:cdab6bc582eedf0c88a1a5',
    messagingSenderId: '532745856576',
    projectId: 'nutri-45d59',
    storageBucket: 'nutri-45d59.appspot.com',
    iosClientId: '532745856576-nt14fqn8mal13tdr3i8iarlu7g27lp3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuclear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm9iu0AK9kNcs332t66a6dgu9OHZJuTLM',
    appId: '1:532745856576:ios:cdab6bc582eedf0c88a1a5',
    messagingSenderId: '532745856576',
    projectId: 'nutri-45d59',
    storageBucket: 'nutri-45d59.appspot.com',
    iosClientId: '532745856576-nt14fqn8mal13tdr3i8iarlu7g27lp3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuclear',
  );
}
